spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stocks-transactions
    username: postgres
    password: postgres
  jpa.hibernate.ddl-auto: update

amazon:
  accessKey: ${AMAZON_ACCESS_KEY}
  secretKey: ${AMAZON_SECRET_KEY}

server:
  tomcat:
    max-threads: 200
